### ISSUE TITLE
Crédits manquants

### ISSUE THREAD

**Issue by prudywsh** [ungdev/EtuUTT#100]
Ça serait faisable une page qui affiche les crédits manquants ? genre le nombre de CS, TM, etc.. encore à faire pour avoir son diplôme.

**Comment by Alabate** [comment]
Non pas avec les données actuelles. On a que accès à la liste des UVs pas aux crédits, donc on sait pas si les gens les ont réussi.

**Comment by gjuchault** [comment]
Sauf si les gens cochent ? (et ça reste stocké)

**Comment by Alabate** [comment]
En effet, on peut très bien faire une page si les gens rentrent les données eux même, dans ce cas là rien est impossible.

On pourrait aussi négocier de récupérer les informations sur demande au près de l'UTT. Genre l'utilisateur clique et ça récupère les données. Mais ça demande d'avoir l'accord du CRI et aussi de dev' une API chez eux.

**Comment by prudywsh** [comment]
et pas possible de charger la page dossier étudiant sur ENT du gars connecté et chopper les infos sur ses crédits ? xD Le token qu'il a eu pour se connecter au site étu fonctionne aussi pour l'ENT non ?

**Comment by BeauneNuits** [comment]
Ces informations sont jugées confidentielles, donc je doute que le CRI agrée. 



De: "Antoine Prudhomme" <notifications@github.com> 
À: "ungdev/EtuUTT" <EtuUTT@noreply.github.com> 
Cc: "Subscribed" <subscribed@noreply.github.com> 
Envoyé: Mercredi 17 Janvier 2018 16:56:52 
Objet: Re: [ungdev/EtuUTT] Crédits manquants (#100) 



et pas possible de charger la page dossier étudiant sur ENT du gars connecté et chopper les infos sur ses crédits ? xD Le token qu'il a eu pour se connecter au site étu fonctionne aussi pour l'ENT non ?

**Comment by Alabate** [comment]
Je connais pas bien CAS, (@BeauneNuits  sera mieux répondre que moi là dessus), mais ça me semblerais pas très cohérent que un site qui a authentifié un utilisateur via CAS puisse s'authentifier en tant que l'utilisateur sur un autre site. C'est un peu le but de CAS d'éviter ça à la base ^^

Et deuxièmement, même si on pouvait (genre en demandant à l'utilisateur d'entrer son mdp chez nous), on ne le ferait en effet sans doute pas parce qu'on tient à garder les accès aux autres données :P

**Comment by BeauneNuits** [comment]
Et @prudywsh , comme vient de le suggérer @Alabate , je confirme que le jeton CAS est signé pour une application, et qu'une tentative de l'utiliser autre part sera rapportée comme une intrusion.
