### ISSUE TITLE
Duplication de semestres

### ISSUE THREAD

**Issue by BeauneNuits** [ungdev/EtuUTT#101]
Le champ 'semestersHistory' présente, pour les individus suivant un semestre de cours à l'UTT en A2017, un duplicata de l'entrée afférente sous l'intitulé P2018. Qu'en est-il ?

**Comment by Alabate** [comment]
J'ai vu, je pense que des que les vrai UV de p18 seront disponible, il remplacera automatiquement, puisque ce sera le même index dans le tableau.
