### ISSUE TITLE
Mettre à jour certaines UE

### ISSUE THREAD

**Issue by ThomasLachaux** [ungdev/EtuUTT#103]
Salut, il y a certaines UE qui n'existent pas sur le site etu et ça serait cool de les ajouter.

Je pense à MATHA02, MATHA03, CHMA11, CHMA12, PHYS11 et PHYS12 ^^

**Comment by ChrisdAutume** [comment]
La synchronisation avec les guides des UES devenant trés compliqués  #com. Est-ce pertinent de mettre en place un formulaire pour ajouter/modifier des ues par les étudiants ?

Si oui, quid d'une modération ?

Ping @arnaud9145 @BeauneNuits

**Comment by HerelAdrastel** [comment]
Je ne sais pas si mettre en place un formulaire pour ajouter/modifier des UEs par les etudiants est intéressant.
J'entends par là qu'il n'a pas souvent d'ajout/suppression d'UEs. Autant les modifier à la main sur la db. ^^

**Comment by ChrisdAutume** [comment]
Ci-joint le csv a modifier, si quelqu'un se chauffe je pourrais insérer les mise à jour dans la db.

[etu_uvs_csv.txt](https://github.com/ungdev/EtuUTT/files/2978152/etu_uvs_csv.txt)

**Comment by HerelAdrastel** [comment]
Plop,

J'ai mis à la jour la plus part des UE TC ainsi que quelques humanités. J'ai vraiment eu la flemme de faire les branches.

[CSV Modifié](https://drive.google.com/file/d/1BMZTj28Yog7W_dmnXfnRYk5feHQKIH-7/view?usp=sharing)

Changelog :

**UEs supprimées (passé isOld à 1)**: TITS, PHYS05, TN4B, C2I1, HT06, HT08, PH19, SO08, SP20
**UEs ajoutées**: PHYS11, PHYS12, CHMA11, CHMA12, MATHA2, MATHA3, RP01, PIX, ST61, ST62, ST63, ST64,ST65,ST66, HT09, HT10, HT11, HT12, HT13, SO09, EV13, GE38

**UEs modifiées:**
TN05 -> ST05
TN09 -> ST09
TN10 -> ST10
TN30 -> ST30
TN31 -> ST31
TN32 -> ST32
TN33 -> ST33
TN40 -> ST40
TN51 -> ST51
TN52 -> ST52

NF04: cs -> tm
SH01: cs -> ct

Heures (juste pour les CS et TM TC) mises à jour

TN07 -> passé en catégorie st

**Comment by ChrisdAutume** [comment]
Merci @HerelAdrastel, mise à jour effectué !
