### ISSUE TITLE
Ajout d'un endpoint dans l'API développeur pour récupérer la liste des événements

### ISSUE THREAD

**Issue by ealionel** [ungdev/EtuUTT#106]
Salut, je sais pas si ça sera traité, mais je laisse ça ici tout de même
Ce serait sympa si quelqu'un pourrait développer cette fonctionnalité, j'en aurais besoin pour notre chatbot.
On aurait par exemple :
`/api/public/events` qui renverrait la liste de tous les événements existants avec système de pagination. Il posséderait également des paramètres de filtrage comme pour `/api/public/users`
Le contenu de la réponse d'un événement pourrait ressembler à :
~~~
{
	start : {date de début de l'événement formaté selon ISO8601}
	end : {date de fin de l'événement formtté selon ISO8601}
	location : {lieu de l'événement}
	title : {nom de l'événement}
	description : {description de l'événement}
	image : {image principale de l'événement}
	media : {une liste des différents médias ajoutés à l'événement}
	organizers : {nom du/des orga(s)}
	link : {un lien vers l'événement fb?}
}
~~~

Egalement ce serait bien que dans le formulaire d'ajout d'événement il y ait une section pour que les organisateurs y glissent le lien Facebook de l'événement.

**Comment by ChrisdAutume** [comment]
Hello,

Toujours d'actualités ?
A noter qu'un événement possède un niveau de visibilité, ainsi ça visibilité peut être privé (nécessite une authentification) ou public.

**Comment by arnaud9145** [comment]
Dans tous les cas je vais en avoir besoin dans les semaines à venir, je créerais l'endpoint moi même je pense :)

**Comment by Ridzu95** [comment]
Hello,

J'en aurais besoin aussi ce serait vachement cool. Ce serait bien en plus de pouvoir faire une requête pour les événements d'un organisateur en particulier si possible ! :D

**Comment by arnaud9145** [comment]
Salut ! L'endpoint a été créé, je vous laisse voir le détails ici : https://etu.utt.fr/api/doc/reference
