### ISSUE TITLE
Donner accès blocks home depuis module

### ISSUE THREAD

**Issue by tgalopin** [ungdev/EtuUTT#11]
Actuellement, la home est générée à la main. Il faut mettre en place le pattern Strategy pour autoriser les modules extérieurs à ajouter des blocks à leur manière.

**Comment by Alabate** [comment]
Pourquoi fermer l'issue ?

**Comment by tgalopin** [comment]
Parce qu'elle est ultra vieille :) . Réouvre si tu veux :)
