### ISSUE TITLE
Erreur 500 lors de la création d'une application externe

### ISSUE THREAD

**Issue by Calinou** [ungdev/EtuUTT#128]
Lors de la création d'une application externe depuis l'interface pour les développeurs, j'obtiens une erreur 500:

```
Request URL: https://etu.utt.fr/api/panel/app/create
Request Method: POST
Status Code: 500 Internal Server Error
```

L'erreur ne semble pas dépendre des champs renseignés dans le formulaire (du moment que les champs requis soient remplis).

**Comment by ChrisdAutume** [comment]
Erreur temporaire lié au stockage mis à disposition par le cluster kubernetes. C'est réctifié !

A noter, que tes services on du être créé malgré l'erreur, seul l'hébergement de l'image des applications était impacté.

Merci pour le signalement,
