### ISSUE TITLE
Ajouter une page /app permettant de télécharger MyUTT

### ISSUE THREAD

**Issue by arnaud9145** [ungdev/EtuUTT#166]
Ajouter une page qui si ouvert sur un mobile propose d'ouvrire le store correspondant au device sinon affiche un QRcode permettant à un mobile d'accéder à cette page. Ajouter le lien de l'application sur Appstore/Playstore est également possible
Si mobile => 
- iOS: Appstore
- Android: Playstore
Si web => affiche un QRCode + liens

S'inspirer du site d'inté : 
https://github.com/ungdev/integration-UTT/blob/master/resources/views/apppage.blade.php

https://github.com/ungdev/integration-UTT/blob/master/public/js/app.js

**Comment by larueli** [comment]
:heavy_check_mark: Testé et fonctionnel.

Le controller `/app` crée une simple redirection vers `http://onelink.to/myutt` qui est un service extérieur qui lui se charge de rediriger l'utilisateur vers le bon store (j'ai mis Apple et Play Store), ou redirige vers une autre page si ordinateur, j'ai simplement téléchargé le QR code de cette page. mis dans le dossier public et redirige vers l'image du QR code `https://etu.utt.fr/onlink_to_myutt_small.png` si ordinateur.
