### ISSUE TITLE
Tri dans la liste des bugs

### ISSUE THREAD

**Issue by arnaud9145** [ungdev/EtuUTT#167]
sur https://etu.utt.fr/bugs, trier les bugs par date et pas criticité

**Comment by BeauneNuits** [comment]
Il me semble plus pertinent de laisser le choix entre les deux tris, plutôt que de le remplacer.
(Déjà vu avec @arnaud9145 )

**Comment by arnaud9145** [comment]
Il pourrait être intéressant de pouvoir trier dans le sens contraire : 
criticité croissante/décroissante
date de création croissante/décroissante

**Comment by BeauneNuits** [comment]
Auquel cas, mieux vaut présenter ça (à mon sens) sous forme de tableau, avec l'en-tête des colonnes permettant de trier. 


De: "Arnaud Dufour" <notifications@github.com> 
À: "ungdev" <EtuUTT@noreply.github.com> 
Cc: "Adrien Rabian" <adrien@rabian.fr>, "Assign" <assign@noreply.github.com> 
Envoyé: Vendredi 18 Octobre 2019 15:11:30 
Objet: Re: [ungdev/EtuUTT] Tri dans la liste des bugs (#167) 



Il pourrait être intéressant de pouvoir trier dans le sens contraire : 
criticité croissante/décroissante 
date de création croissante/décroissante
