### ISSUE TITLE
[API] Authoriser une application quand utlisateur non connecté

### ISSUE THREAD

**Issue by supertinou** [ungdev/EtuUTT#17]
### Authoriser une application qd non connecté

Il serait très intéressant lorsque l'on veut authoriser une application externe EtuUTT via l'url
__/api/oauth/authorize?response_type=code&client_id=<your_client_id>__
et que l'on n'est pas connecté au site EtuUTT que le message "Vous n'êtes pas authorisé a voir cette page" s'affiche mais plutôt "Connecter vous d'abord au site pour authoriser l'application" puis que lorsque l'on se connecte sur le site étu, on soit redirigé à la fin vers la page d'authorisation de l'application qui a le client_id.

**Comment by tgalopin** [comment]
Je l'ai fait mais j'avais pas les droits jusqu'à peu pour le push (nettoyage de Github par Hugo).

**Comment by supertinou** [comment]
:+1:
