### ISSUE TITLE
Rendre les wiki accessible à etu.utt.fr/wiki

### ISSUE THREAD

**Issue by jdorel** [ungdev/EtuUTT#197]
Actuellement, la liste des wiki est accessible à etu.utt.fr/wiki/list. Une redirection depuis etu.utt.fr/wiki semble approprié pour faciliter l'accès.

**Comment by larueli** [comment]
En gros tu veux une redirection simple de https://etu.utt.fr/wiki vers https://etu.utt.fr/wiki/list ?

**Comment by jdorel** [comment]
Yep

**Comment by larueli** [comment]
J'ai fait mieux que ça, le commit que j'ai fait change simplement la route /wiki/list vers /wiki, donc pas besoin de redirection supplémentaire. Les autres wiki ne sont pas affectés.
