### ISSUE TITLE
Erreur sur l'upload de logo asso

### ISSUE THREAD

**Issue by Darynh** [ungdev/EtuUTT#22]
Hello,

Depuis un compte asso, upload un logo sur "Administration" >> "Modifier votre logo" >> "Envoyer" fait tomber sur une erreur `Failed to load resource: the server responded with a status of 500 (Internal Server Error)`

Par ailleurs, le logo par défaut provoque des erreurs dans la console :
> GET https://etu.utt.fr/logos/default-logo.png?v10.1.4?6d51a 404 (Not Found) orga:1 
> GET https://etu.utt.fr/facebox/closelabel.png 404 (Not Found) orga:1
> GET https://etu.utt.fr/facebox/loading.gif 404 (Not Found) loading.gif:1
> GET https://etu.utt.fr/facebox/loading.gif 404 (Not Found) default-logo.png:1
> GET https://etu.utt.fr/logos/default-logo.png?v10.1.4?6d51a 404 (Not Found)

**Comment by nashe** [comment]
Désolé du délais ! Je pense que c'était juste un soucis de permissions.

Est-ce que tu peux retenter et me dire si ça marche, désormais ?

Merci :+1:
