### ISSUE TITLE
Ajout des spécialités de Masters dans la recherche

### ISSUE THREAD

**Issue by nashe** [ungdev/EtuUTT#40]
> je viens de caler que dans le trombi, si la recherche par branche+semestre fonctionne très bien... elle est limitée aux ingénieurs, de fait.
> Ce serait génial de rajouter chaque spécialité de master dedans, je ne pense pas que ça prenne trop de temps
> (non parce que retourner sur l'ENT pour trouver, là, ça me pique le fondement ! :D )

Message original : https://etu.utt.fr/bugs/229-et-les-master

Les spécialités existantes à l'UTT sont les suivantes :
- IM 
  - IMSGA
  - IMEDD
  - SMI-LES
- STIC
  - OSS
  - SSI
- MP
  - ONT
  - TEMMA
  - IAMC
  - MERI

Le format utilisé pour l'affichage sur le profil est `SectionSemestre Spécialité` (STIC4 SSI, MP2 ONT...).

**Comment by nashe** [comment]
(Pour résumer le problème et pourquoi ça n'est pas si simple, c'est que les masters SSI sont en fait STIC mais filière SSI, or il n'y a pas de recherche par filière pour le moment).

**Comment by nashe** [comment]
(Pour résumer le problème et pourquoi ça n'est pas si simple, c'est que les masters SSI sont en fait STIC mais filière SSI, or il n'y a pas de recherche par filière pour le moment).

**Comment by larueli** [comment]
Je vais travailler dessus
