### ISSUE TITLE
Faciliter l'insertion d'images dans le Daymail

### ISSUE THREAD

**Issue by nashe** [ungdev/EtuUTT#44]
Lors de la mise en ligne d'une image pour le Daymail, il faut copier-coller le lien à la main pour ensuite l'insérer dans le corps du message.

>  Ça serait bien d'ajouter un petit bouton pour inclure l'image dans le post après upload ! 

Message original : https://etu.utt.fr/bugs/81-envoi-d-image#4

**Comment by Alabate** [comment]
fixed by 61856c352be7da5fc38f539ee20e4d8615d2100d
