### ISSUE TITLE
UVS manquantes

### ISSUE THREAD

**Issue by nashe** [ungdev/EtuUTT#47]
Il manque au moins les UVs suivantes sur le site : 

- NF14 (https://etu.utt.fr/bugs/250-uv-manquante)
- C2I1 (https://etu.utt.fr/bugs/250-uv-manquante#1)
- MQ05 (https://etu.utt.fr/bugs/219-uv-manquante#4)
- TN78 (https://etu.utt.fr/bugs/249-uvs-manquantes#1)
- SH1 (https://etu.utt.fr/bugs/246-uvs-manquantes#1)
- GL02 (https://etu.utt.fr/bugs/246-uvs-manquantes#1)
- IF07 (https://etu.utt.fr/bugs/246-uvs-manquantes#1)
- RE14 (https://etu.utt.fr/bugs/231-uv-manquante-re14#1)

@tgalopin : À ton avis, on doit forcément refaire un parseur de guide des UV qui fonctionne correctement ou on peut se permettre de les rajouter à la main ?

**Comment by tgalopin** [comment]
Le parser est pas fiable, mais j'avais démarré un truc avec le CRI pour faire une API chez eux. Je sais plus où ca en est mais ca vaut le coup de voir ca, et au pire retravailler avec eux pour finaliser.

Sinon, si c'est pas possible, le parser était dégueulasse : mieux vaut le faire à la main à mon avis.

**Comment by nashe** [comment]
Tout est réglé avec le nouveau parser proposé dans #51 par @ALabate (merci <3)
