### ISSUE TITLE
Timezone et locale

### ISSUE THREAD

**Issue by Alabate** [ungdev/EtuUTT#61]
Nous avons eu un signalement de bug sur le site etu indiquant un décalage horaire de 2h entre la page "Les derniers" du module de covoit et lorsqu'on regarde une annonce en particulier. Or on est en heure d'été, donc une heure affiché en gmt, l'autre en locale. La bonne horaire entrée par l'utilisateur était celle de la page décrivant le covoit.

Sauf que en local quand j'ai testé, chez moi tout marchait. Ça dépend donc juste de la conf du seveur, et c'est pas trop normal. [J'ai réglé un peu de façon moche le problème](https://github.com/ungdev/EtuUTT/commit/a0fdab1a4f15d6d0e7638c197ede4d94b309dcc2) en précisant la timezone de paris sur l'affichage des derniers covoit. Sauf que du coup en local, maintenant j'ai un décallage..

Bref, il faut regarder ça plus en détail et réfléchir sur quelle timezone on travaille : paris uniquement ? Réglable par l'utilisateur sur son profil ? A préciser lorsqu'on met une date sur le module de covoit ?

**Comment by nashe** [comment]
La timezone utilisée par défaut par PHP est dans le `php.ini`. Je vais vérifier si ça a été mis correctement sur Paris (au moins spécifier la timezone du serveur).
