### ISSUE TITLE
Trombi avec le personnel de l'UTT

### ISSUE THREAD

**Issue by Alabate** [ungdev/EtuUTT#62]
L'import du LDAP prend aussi les enseignants et personnels de l'UTT, ainsi que leurs infos publiques tel que leurs bureaux.

Pourquoi ne pas les avoir sur le trombi, eux aussi ?

**Comment by nashe** [comment]
Vu que le trombi avait surtout vocation à gérer les étudiants, peut-être qu'un trombi « Personnel » serait plus approprié ? Ça mérite de demander au CRI si on a aussi le droit de les importer et les afficher (je pense plus particulièrement à tout ce qui touche le droit à la rectification/modification des données, peut-être qu'il faudrait aussi leur faire un système de compte si on ne se synchronise pas tous les jours avec le LDAP… bref ça complique la chose).

**Comment by ALabate** [comment]
De toute façon, c'est vrai que ce n'est pas les mêmes critères de recherche, donc une autre page de recherche serait plutot logique, en effet.

Pour ce qui est du droit de rectification et modification, c'est exactement les mêmes circonstances avec les étudiants. Les profs peuvent se connecter au site etu et ils sont déjà en base de donnée (essaye sur l'interface admin, tu peux te connecter en tant qu'un prof et modifier ton profil). D'ailleurs, on peut déjà accéder à leur profils via `http://etuutt/user/[loginDunProf]`. Bon après, la modif du profil et l'affichage n'est pas adapté puisqu'il ne propose pas les bonnes cases comme le numéro de bureau, le service, etc (qui sont pourtant déjà en BDD).

Du coup, pour moi les étapes sont :

* Envoyer un email au cri pour savoir ce qu'ils en pensent, s'ils trouvent ça génant
* Adapter le formulaire de modif de profil
* Adapter la page de profil publique
* Faire un autre formulaire calqué sur le trombi, mais avec eux uniquement, avec d'autres critères.

Ca me semble pas si difficile, non ?

**Comment by nashe** [comment]
Yep, à voir en fonction de leur réponse ! Peut-être qu'il faudra aussi les prévenir qu'ils disposent d'un profil, je pense que beaucoup ne le savent pas… Et s'assurer des paramètres de confidentialité (commentaires sur les UV, annales…) qui existent déjà. Peut-être leur créer un forum, aussi ?

N'hésite pas à découper ça en plusieurs *enhancements* !

**Comment by ALabate** [comment]
Oui, y'a des chances.. Après, y'a des risques que certains profs n'apprécient pas :/

Pour l'instant je laisse tout ensemble pour pas polluer la liste des issues, et ça sert pas à grand chose de faire que la moitié. (un profil de prof propre ne sert pas à grand chose sans un trombi prof pour moi). Pour le forum, on va déjà essayer de faire en sorte que les etu l'utilisent, après on verra le reste ^^

Pour ce qui est des problèmes de confidentialité, ça devrait être bientôt réglé. Comme avec l'arrivée des télés, on aura sans doute un module qui sera géré par la com' du BDE, puis potentiellement d'autres pour le bureau BDE, il va falloir créer différents profils regroupant plusiers droits, et avoir une liste des gens qui ont des accès. Du coup je suis en train de retaper toute la partie connexion (autant CAS que externe) ainsi que les droits pour tout mettre sur le système *security* de symfony avec les roles qui nous permettrons de faire facilement des profils. Du coup je vais être amené à modifier chaque page pour remplacer toutes les allusions aux droits et donc forcément je vais vérifier un peu tous les points de vus une fois que j'aurais terminé.
