### ISSUE TITLE
Amélioration trombinoscope : recherche formation

### ISSUE THREAD

**Issue by BeauneNuits** [ungdev/EtuUTT#76]
Pouvoir affiner la recherche par formation : ingé / master, branche / type master, filière / spé master.

**Comment by nashe** [comment]
Si jamais tu arrives à intégrer #40 en même temps, ça serait très utile !

**Comment by nashe** [comment]
@arnaud9145 : tu as besoin d'un coup de main, ou alors tu n'as pas eu l'occasion de te te mettre sur le sujet ? :)

**Comment by arnaud9145** [comment]
Pas eu le temps pour l'instant mais merci ^^ 


De: "Thomas Chauchefoin" <notifications@github.com> 
À: "ungdev/EtuUTT" <EtuUTT@noreply.github.com> 
Cc: "arnaud9145" <arnaud.dufour@utt.fr>, "Mention" <mention@noreply.github.com> 
Envoyé: Mardi 9 Mai 2017 14:29:30 
Objet: Re: [ungdev/EtuUTT] Amélioration trombinoscope : recherche formation (#76) 



@arnaud9145 : tu as besoin d'un coup de main, ou alors tu n'as pas eu l'occasion de te te mettre sur le sujet ? :)

**Comment by arnaud9145** [comment]
Fail du reply all :/ 

Je disais j'ai pas trop eu le temps, je m'y remettrai plus tard ^^ 


De: "Thomas Chauchefoin" <notifications@github.com> 
À: "ungdev/EtuUTT" <EtuUTT@noreply.github.com> 
Cc: "arnaud9145" <arnaud.dufour@utt.fr>, "Mention" <mention@noreply.github.com> 
Envoyé: Mardi 9 Mai 2017 14:29:30 
Objet: Re: [ungdev/EtuUTT] Amélioration trombinoscope : recherche formation (#76) 



@arnaud9145 : tu as besoin d'un coup de main, ou alors tu n'as pas eu l'occasion de te te mettre sur le sujet ? :)

**Comment by larueli** [comment]
Je vais travailler dessus
