### ISSUE TITLE
nginx sert les fichiers en .php

### ISSUE THREAD

**Issue by nashe** [ungdev/EtuUTT#86]
Visiblement, `nginx` est mal configuré et n’interprète pas toujours les fichiers en `.php` : 

```
$ curl -vv https://etu.utt.fr/app_dev.php
[...]
< HTTP/1.1 200 OK
< Server: nginx
< Date: Mon, 28 Aug 2017 19:39:39 GMT
< Content-Type: application/octet-stream
< Content-Length: 1281
< Connection: keep-alive
< Last-Modified: Wed, 15 Feb 2017 12:53:48 GMT
< ETag: "58a44f5c-501"
< X-Frame-Options: SAMEORIGIN
< X-Content-Type-Options: nosniff
< X-XSS-Protection: 1; mode=block
< Cache-Control: no-transform
< X-UA-Compatible: IE=Edge
< Accept-Ranges: bytes
< Access-Control-Allow-Origin: *
<
<?php

use Symfony\Component\Debug\Debug;
use Symfony\Component\HttpFoundation\Request;

// If you don't want to setup permissions the proper way, just uncomment the following PHP line
// read http://symfony.com/doc/current/book/installation.html#checking-symfony-application-configuration-and-setup
// for more information
//umask(0000);
[...]
```

**Comment by Alabate** [comment]
Nginx est configuré pour n'executer que `app.php`, et c'est selon moi une bonne chose qu'il ne soit pas capable d’exécuter d'autres fichiers qui se trouveraient là. Cependant, même si en théorie, tous les fichiers php sont publiques, je viens quand même d'ajouter une règle pour deny l'accès aux fichiers php, yml et sql. Ça coûte rien, et ça pourrait éviter de rendre publique des fichiers privés qui se trouveraient dans le mauvais dossier.

Cette solution te convient ?

**Comment by nashe** [comment]
Yep, merci :-)
